### ISSUE TITLE
Fedora sha check fails

### ISSUE THREAD

**Issue by acozine** [acozine/sufia-centos#49]
The hydra-stack role now fails with:

```
msg: The SHA-256 checksum for /opt/install/fcrepo-webapp-4.5.0.war did not match b9781a38227b71bb2f61d09938f15d5621d57edcfb94db5e9524abcac6984b14; it was f9c778c4285dcbb7ab228f43e5e30ea7511a5553ca52a34e274e1e390cb5187e.
```

When I look at the downloads page https://github.com/fcrepo4/fcrepo4/releases I only see SHA1 and MD5 hashes.
@dunn - where did you get the SHA-256 value?

**Comment by dunn** [comment]
Probably was still using the GitHub version, sorry!

**Comment by dunn** [comment]
(On your recommended I switched back to the Maven source.)
