### ISSUE TITLE
move alexandria-v2 role to ADRL repository

### ISSUE THREAD

**Issue by dunn** [acozine/sufia-centos#64]
Since it's all ADRL-specific stuff anyway, we'd like to migrate the `alexandria-v2` role to `ansible/` in the ADRL repository.  Since our playbooks are already in there anyway, the current workflow is to symlink the roles from this repository into that directory.  This would let that remain the same, while letting `sufia-centos` retain its generality; in the future we would be able to add more roles to that directory if we needed to.

cc @ilessing @johnajao

**Comment by ilessing** [comment]
Alex and I discussed this and Alex will try to find a way to not rely on symlinks to roles.  This issue is duplicated in Jira: DIGREPO-469 on purpose.

**Comment by acozine** [comment]
Keeping the alexandria-v2 role in the general repository is fine. I propose two changes:  
1. Separate the project-specific tasks from the environment-specific tasks. Changes to application.yml and cloning adrl-dm need to happen on EC2 and Vagrant as well as in the UCSB environment, while automount is not necessary in EC2 or Vagrant. Having a role for the project and a role for the environment (vSphere or UCSB) would make that distinction clear. Is there any chance other institutions might find the automount tasks useful?  
2. Put the environment-specific tasks at the end of the playbook. This makes it easier to spot and skip when building in other environments.

**Comment by dunn** [comment]
> Is there any chance other institutions might find the automount tasks useful?

Right now I'm not sure if it'll work for other SMB setups, let alone other protocols; but I'd be happy to see it generalized if possible.

**Comment by dunn** [comment]
PRs
- https://github.com/acozine/sufia-centos/pull/68
- https://github.com/curationexperts/alexandria-v2/issues/572
