### ISSUE TITLE
get rid of ezid.yml

### ISSUE THREAD

**Issue by acozine** [acozine/sufia-centos#71]
User and password are now in secrets.yml. Put host and port in application.yml. See https://github.com/curationexperts/alexandria-v2/pull/576 for more info.

**Comment by dunn** [comment]
:ok_woman: https://github.com/curationexperts/alexandria-v2/commit/02d5b16553b735bbffe77249e2eb94822ddea887

**Comment by acozine** [comment]
Needs to be implemented here: https://github.com/acozine/sufia-centos/blob/master/roles/ezid/tasks/main.yml#L20

**Comment by dunn** [comment]
Oh, I'm in the wrong repository :see_no_evil:

**Comment by dunn** [comment]
Should we add some `lineinfile` writes to `application.yml`?  That would require adding a `application.yml.j2` template, and tweaking the alexandria-v2 role.

**Comment by acozine** [comment]
I don't think `lineinfile` requires a template - you can write to system files with it.

**Comment by dunn** [comment]
I meant that without the `alexandria-v2` role, Ansible doesn't currently create an `application.yml` in the shared Capistrano directory.  So if we want the `ezid` role to modify `application.yml`, we'd either need to have a `application.yml.j2` template outside of `alexandria-v2`, or have a pair of conditional tasks—`ezid` writes to `application.yml` if it exists, or else creates it from scratch.  Right?

**Comment by acozine** [comment]
Oh, I see what you mean. Yes, that is correct. If we are moving toward a model where all non-secret config variables are kept in application.yml and all secret config variables are kept in secrets.yml (and I think that's a good goal - it makes capifying codebases easier, among other things), then I vote for a small role that creates a vanilla application.yml in the shared directory, with subsequent roles/tasks for all the things that need to be added. So the other config roles, including ezid, ldap, and the alexandria-specific role, would use `lineinfile` to add to existing files.

**Comment by dunn** [comment]
> then I vote for a small role that creates a vanilla application.yml in the shared directory

Any reason not to include it in `hydra-stack`?

**Comment by acozine** [comment]
The hydra-stack role is for the underlying components - Solr and Fedora. I think the task for creating application.yml would fit better in the app-config role.
